### ISSUE TITLE
Don't commit tags / git commit if publishing fails

### ISSUE THREAD

**Issue by jkelleyrtp** [pksunkara/cargo-workspaces#162] opened 2024-07-18 19:33 UTC
I frequently run into issues with this (fantastic!) command due to some edge cases in our large repo and then my repo has a commit and a tag still sitting around even though publishing failed.

It'd be much better if the tag/commit were added *after* a successful publish or was somehow unwindable rather than me having to peck around for git reset + git tag --delete.

**Comment by pksunkara** [comment] 2024-07-19 10:33
Duplicate of #13.

I would appreciate it if you could list the needed things here. I haven't encountered this issue and thus will not be perfect in implementing this. What should I revert in version failure and publish failure?

**Closed by pksunkara** 2024-07-19 10:33 UTC
