### ISSUE TITLE
workspace create does not show option for 2021 edition

### ISSUE THREAD

**Issue by vikigenius** [pksunkara/cargo-workspaces#63] opened 2022-01-06 01:20 UTC
`cargo ws create` does not provide me with the option to chose 2021 edition. It shows only 2015 and 2018.

This despite `cargo new` using 2021 by default.

I am also using the latest release 0.2.28

**Comment by shymega** [comment] 2022-01-11 14:30
Looks like this has been implemented in 1b004edc9ae8e26ff19b946d6b344942e6306ccd - a new release needs to be made. I too had this issue, but the sources would indicate it's been fixed.

I just built the tool from that commit, and I can confirm the 2021 edition is now accessible.

**Comment by pksunkara** [comment] 2022-02-11 01:20
Released in 0.2.29

**Closed by pksunkara** 2022-02-11 01:20 UTC
